name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.3.2"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Dependencies
        working-directory: ./day1
        run: gleam deps download
      - name: Tests
        working-directory: ./day1
        run: gleam test
      - name: Format
        working-directory: ./day1
        run: gleam format --check src test
        
